The world is moving toward artificial intelligence. There are two main components of it: deep learning and machine learning. Without deep learning and machine learning, it is impossible to visualize artificial intelligence

# Machine Learning and Deep Learning

Machine Learning and Deep Learning are both types of AI. Machine Learning uses algorithms to parse data, learn from that data, and make informed decisions based on what it has learned. Deep Learning, on the other hand, structures algorithms in layers to create an “artificial neural network” that can learn and make intelligent decisions on its own. Deep Learning is a subset of Machine Learning.

Machine Learning provides excellent performances on a small/medium dataset, whereas Deep Learning provides excellent performance on a big dataset. Machine Learning works on a low-end machine, while Deep Learning requires a powerful machine, preferably with GPU. Machine Learning execution time ranges from few minutes to hours, whereas Deep Learning takes up to weeks.

In short, Machine Learning is AI that can automatically adapt with minimal human interference. Deep learning is a subset of machine learning that uses artificial neural networks to mimic the learning process of the human brain.

Machine Learning is a type of AI that uses algorithms to parse data, learn from that data, and make informed decisions based on what it has learned. Here are some examples of machine learning in action:

* Linear regression
* Decision trees
* Random forest
* XGBoost
* Recommendation engines (e.g. Netflix)
* Sorting, tagging and categorizing photos (e.g. Yelp)
* Self-Driving Cars (e.g. Waymo)
* Education (e.g. Duolingo)
* Customer Lifetime Value (e.g. Asos)
* Patient Sickness Predictions (e.g. KenSci)
* Determining Credit Worthiness (e.g. Deserve)
* Targeted Emails (e.g. Optimail)
* Image recognition
* Speech recognition
* Virtual personal assistants
* Customer service reps
* Social media algorithms
* Fraud detection
* Streaming recommendations
* Traffic predictions

These are just a few examples of how machine learning is being used in the real world to improve our daily lives and make informed decisions.

Deep Learning is a subset of Machine Learning that uses artificial neural networks to mimic the learning process of the human brain. Here are some examples of deep learning in action:

* Virtual assistants (e.g. Alexa, Cortana, Siri)
* Self-driving cars
* Chatbots
* Facial recognition
* Medical science
* Speech recognition

These are just a few examples of how deep learning is being used in the real world to improve our daily lives and make informed decisions.

AI is like a robot that can think and learn like a human. Machine Learning is when the robot learns by looking at lots of examples and figuring out what they have in common. Deep Learning is when the robot learns by looking at lots of examples, but it also tries to understand how the human brain works and learns in the same way. So, Machine Learning is like learning from a book, while Deep Learning is like learning from a book and also trying to think like a human.

# PyTorch

PyTorch is the most optimized high-performance tensor library for computation of deep learning tasks on GPUs (graphics processing units) and CPUs (central processing units). The main purpose of PyTorch is to enhance the performance of algorithms in large-scale computing environments. PyTorch is a library based on Python and the Torch tool provided by Facebook’s Artificial Intelligence Research group, which performs scientific computing.

NumPy-based operations on a GPU are not efficient enough to process heavy computations. Static deep learning libraries are a bottleneck for bringing flexibility to computations and speed. From a practitioner’s point of view, PyTorch tensors are very similar to the N-dimensional arrays of a NumPy library based on Python. The PyTorch library provides bridge options for moving a NumPy array to a tensor array, and vice versa, in order to make the library flexible across different computing environments.

Although PyTorch provides a large collection of libraries and modules for computation, three modules are very prominent.

* Autograd. This module provides functionality for automatic differentiation of tensors. A recorder class in the program remembers the operations and retrieves those operations with a trigger called backward to compute the gradients. This is immensely helpful in the implementation of neural network models.

* Optim. This module provides optimization techniques that can be used to minimize the error function for a specific model. Currently, PyTorch supports various advanced optimization methods, which includes Adam, stochastic gradient descent (SGD), and more.

* NN. NN stands for neural network model. Manually defining the functions, layers, and further computations using complete tensor operations is very difficult to remember and execute. We need functions that automate the layers, activation functions, loss functions, and optimization functions and provides a layer defined by the user so that manual intervention can be reduced. The NN module has a set of built-in functions that automates the manual process of running a tensor operation.


Every learning system requires three things: input data, processing, and an output layer.

# Types of learning

In a deep learning system, more than one layer of a learning algorithm is deployed. In machine learning, we think of supervised, unsupervised, semisupervised, and reinforcement learning systems.

* A supervised machine-learning algorithm is one where the data is labeled with classes or tagged with outcomes. We show the machine the input data with corresponding tags or labels. The machine identifies the relationship with a function. Please note that this function connects the input to the labels or tags.

* In unsupervised learning, we show the machine only the input data and ask the machine to group the inputs based on association, similarities or dissimilarities, and so forth.

* In semisupervised learning, we show the machine input features and labeled data or tags; however we ask the machine to predict the untagged outcomes or labels.

* In reinforcement learning, we introduce a reward and penalty mechanism, where every correct action is rewarded and every incorrect action is penalized.


In all of these examples of machine learning algorithms, we assume that the dataset is small, because getting massive amounts of tagged data is a challenge, and it takes a lot of time for machine learning algorithms to process large-scale matrix computations. Since machine learning algorithms are not scalable for massive datasets, we need deep learning algorithms.

# Machine learning vs Deep learning task example

Natural language is an important part of artificial intelligence. We need to develop systems that understand natural language and provide responses to the agent. Let’s take an example of machine translation, where a sentence in language 1 (French) can be converted to language 2 (English), and vice versa. To develop such a system, we need a large collection of English-French bilingual sentences. The corpus requirement is very large, as all the language nuances need to be covered by the model.

After preprocessing and feature creation, you can observe hundreds of thousands of features that need to be computed to produce output. If we train a machine learning supervised model, it would take months to run and to produce output. To achieve scalability in this task, we need deep learning algorithms, such as a recurrent neural network. This is how the artificial intelligence is connected to deep learning and machine learning.

# Recipe 1-1. Using Tensors

The data structure used in PyTorch is graph based and tensor based, therefore, it is important to understand basic operations and defining tensors.


# Tensor operations

The x object is a list. We can check whether an object in Python is a tensor object by using the following syntax.

Typically, the is_tensor function checks and the is_storage function checks whether the object is stored as tensor object.

## is_tensor, is_storage function

In [ ]:
import torch

x = [0,1,2,3,4,5,6,7,8,9]

In [ ]:
torch.is_tensor(x)

False

In [ ]:
torch.is_storage(x)

False

Now, let’s create an object that contains random numbers from Torch, similar to NumPy library. We can check the tensor and storage type.

In [ ]:
y = torch.randn(1,2,3,4,5)

In [ ]:
torch.is_tensor(y)

True

In [ ]:
torch.is_storage(y)

False

In [ ]:
a = torch.FloatStorage(6)
a

 -1.2188698747195303e-05
 3.3362113838645245e-41
 -1.1531737982295454e-05
 3.3362113838645245e-41
 4.484155085839415e-44
 0.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [ ]:
torch.is_storage(a)

True

In [ ]:
torch.numel(y)  # number of elements

120

In [ ]:
y

tensor([[[[[ 0.0190,  0.0220,  1.1532, -0.3393,  0.1559],
           [ 0.8966, -0.2968,  1.5985, -0.0496, -1.2485],
           [-0.8509, -0.7690, -1.5606, -0.5309,  0.2178],
           [ 1.3232, -0.5660,  0.3566, -0.4535, -0.2971]],

          [[-1.5380, -1.0248, -0.3781,  0.9257,  0.5158],
           [-1.0042,  0.9860,  1.1334,  0.8504,  1.0534],
           [ 0.3692,  0.0628, -0.6125,  0.7500, -0.7346],
           [ 0.4622,  1.1759,  0.2145,  0.5362,  0.1407]],

          [[-2.3332,  1.5308,  0.2680,  0.4505, -0.2725],
           [-1.7399,  0.1299,  0.8519, -0.2829,  0.0731],
           [-1.3880, -0.2678, -0.1254, -1.5038, -0.3287],
           [ 0.7388, -1.4770, -1.2222, -0.2746, -0.3450]]],


         [[[-0.7162,  0.5781,  0.3805, -0.6780, -2.6740],
           [ 1.5984,  0.8021, -0.3511, -0.0670, -0.0534],
           [-0.8315,  0.9570,  1.2647, -0.2753, -0.1325],
           [ 0.1062,  0.0924, -1.1821,  0.2129,  0.1469]],

          [[-0.6526,  0.7180, -0.4495, -0.7186,  0.6839],
    

## torch.zeros

The following script is another example of creating zero values in a 2D tensor and counting the numerical elements in it.

In [ ]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.numel(torch.zeros(4,4))

16

## torch.eye

Like NumPy operations, the eye function creates a diagonal matrix, of which the diagonal elements have ones, and off diagonal elements have zeros. The eye function can be manipulated by providing the shape option. The following example shows how to provide the shape parameter.

In [ ]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [ ]:
torch.eye(5,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

## torch.linspace

Linear space and points between the linear space can be created using tensor operations. Let’s use an example of creating 25 points in a linear space starting from value 2 and ending with 10. Torch can read from a NumPy array format.


In [ ]:
import numpy as np

x1 = np.array(x)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.from_numpy(x1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.linspace(2, 10, steps=25)  # linear spacing

tensor([ 2.0000,  2.3333,  2.6667,  3.0000,  3.3333,  3.6667,  4.0000,  4.3333,
         4.6667,  5.0000,  5.3333,  5.6667,  6.0000,  6.3333,  6.6667,  7.0000,
         7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,  9.6667,
        10.0000])

## torch.logspace

The difference between linear and logarithmic spacing is in how the values are spaced along an axis. On a linear scale, the values are equally spaced, meaning that the difference between any two consecutive values is always the same. On a logarithmic scale, the values are spaced such that the ratio between any two consecutive values is always the same. This means that on a logarithmic scale, the values increase exponentially, with larger and larger gaps between consecutive values as you move along the axis.

For example, consider a linear scale from 1 to 100 with 10 equally spaced values: 1, 11, 21, 31, 41, 51, 61, 71, 81, and 91. The difference between any two consecutive values is always 10. Now consider a logarithmic scale from 1 to 100 with 10 equally spaced values: 1, 10, 100, 1000, and so on. The ratio between any two consecutive values is always 10.

Linear scales are useful when the data being plotted has a relatively small range of values or when the differences between the values are important. Logarithmic scales are useful when the data being plotted spans several orders of magnitude or when the ratios between the values are important.

In [ ]:
torch.logspace(start=-10, end=10, steps=25)  # logarithmic spacing

tensor([1.0000e-10, 6.8129e-10, 4.6416e-09, 3.1623e-08, 2.1544e-07, 1.4678e-06,
        1.0000e-05, 6.8129e-05, 4.6416e-04, 3.1623e-03, 2.1544e-02, 1.4678e-01,
        1.0000e+00, 6.8129e+00, 4.6416e+01, 3.1623e+02, 2.1544e+03, 1.4678e+04,
        1.0000e+05, 6.8129e+05, 4.6416e+06, 3.1623e+07, 2.1544e+08, 1.4678e+09,
        1.0000e+10])

## Normal and uniform distribution

torch.randn and torch.rand are two functions in PyTorch that can be used to generate random numbers

* torch.randn returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution). The shape of the tensor is defined by the variable argument size.

* torch.rand returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1). The shape of the tensor is defined by the variable parameter sizes.

In summary, the main difference between torch.randn and torch.rand is the distribution from which the random numbers are drawn. torch.randn generates random numbers from a normal distribution, while torch.rand generates random numbers from a uniform distribution.

A normal distribution, also known as a Gaussian distribution, is a type of continuous probability distribution that is often used in statistics and other fields to represent real-valued random variables whose distributions are not known. The normal distribution is defined by two parameters: the mean, which specifies the center of the distribution, and the standard deviation, which specifies the spread of the distribution.

The normal distribution has a bell-shaped curve, with the highest point at the mean and the curve falling off symmetrically on either side. The standard deviation determines how spread out the curve is. A larger standard deviation means that the curve is more spread out, while a smaller standard deviation means that the curve is more concentrated around the mean.

The normal distribution is widely used in many fields because it often provides a good approximation to the distribution of many types of data. For example, it can be used to model measurement errors, stock returns, and many other types of data.

Random number generation is a common process in data science to generate or gather sample data points in a space to simulate structure in the data. Random numbers can be generated from a statistical distribution, any two values, or a predefined distribution. Like NumPy functions, the random number can be generated using the following example. Uniform distribution is defined as a distribution where each outcome has equal probability of happening; hence, the event probabilities are constant.

In statistics, uniform distribution refers to a type of probability distribution in which all outcomes are equally likely. For example, when flipping a coin, the probability of getting either heads or tails is the same. This is an example of a discrete uniform distribution, where the outcomes are discrete and have the same probability.

There are two types of uniform distributions: discrete and continuous. In a discrete uniform distribution, the outcomes are discrete and have the same probability. In a continuous uniform distribution, the outcomes are continuous and infinite.

The uniform distribution can be visualized as a straight horizontal line. For example, for a coin flip returning heads or tails, both have a probability of 0.50 and would be depicted by a line from the y-axis at 0.501. The formula for a discrete uniform distribution is f(x) = 1 / (b - a + 1) for x = a, a + 1, ..., b, where a is the smallest value and b is the largest value.

### torch.rand

In [ ]:
# random numbers from a uniform distribution between the values 0 and 1
torch.rand(10)

tensor([0.2153, 0.2073, 0.4758, 0.0586, 0.8958, 0.5129, 0.7490, 0.2254, 0.4485,
        0.5658])

The following script shows how the random number from two values, 0 and 1, are selected. The result tensor can be reshaped to create a (4,5) matrix. The random numbers from a normal distribution with arithmetic mean 0 and standard deviation 1 can also be created, as follows.


In [ ]:
torch.rand(4,5)

tensor([[0.3631, 0.9719, 0.2716, 0.6552, 0.1607],
        [0.4408, 0.3674, 0.7157, 0.8493, 0.6216],
        [0.4546, 0.3720, 0.8920, 0.3819, 0.8610],
        [0.2775, 0.9121, 0.9980, 0.8427, 0.7868]])

### torch.randn

In [ ]:
# random numbers from a normal distribution with mean=0 and standard deviation=1
torch.randn(10)

tensor([-0.3120,  0.0220,  0.8794, -0.2567, -0.7330,  0.8952,  0.6341, -0.7475,
        -0.3016, -1.1492])

In [ ]:
torch.randn(4,5)

tensor([[ 3.0292,  0.1858, -0.1704,  1.0270, -1.1049],
        [ 0.1970, -0.1435,  1.4660, -0.1042, -0.1376],
        [ 0.3774,  0.4664, -0.4066, -1.2096,  0.0365],
        [ 0.8257, -0.6476, -1.8021,  2.4911,  0.7702]])

### torch.normal

In PyTorch, you can generate random numbers from a normal distribution with a specified mean and standard deviation using the torch.normal function. This function takes two arguments: mean, which specifies the mean of the distribution, and std, which specifies the standard deviation of the distribution.

In [ ]:
torch.normal(mean=5, std=10, size=(3,3))

tensor([[-3.8104, 31.0323,  3.5231],
        [15.8778, 16.8216, 10.7986],
        [-1.0500, -3.7557, 17.0463]])

## rand.perm

To select random values from a range of values using random permutation requires defining the range first. This range can be created by using the arrange function. When using the arrange function, you must define the step size, which places all the values in an equal distance space. By default, the step size is 1.


In [ ]:
# selecting values from a range, this is called random permutation
torch.randperm(10)

tensor([1, 5, 2, 7, 0, 6, 8, 4, 9, 3])

In [ ]:
# usage of range function
torch.arange(10, 40, 2)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [ ]:
torch.arange(10, 40)  # step size=1

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

## torch.argmin, torch.argmax

To find the minimum and maximum values in a 1D tensor, argmin and argmax can be used. The dimension needs to be mentioned if the input is a matrix in order to search minimum values along rows or columns.

In [ ]:
d = torch.randn(4,5)
d

tensor([[-1.1206, -1.6680,  1.0685, -0.1831, -1.5684],
        [ 1.3443,  0.0372, -0.3598,  0.1032, -1.6268],
        [ 0.5729, -0.6995, -2.1433, -0.5419, -0.4255],
        [ 1.8125, -1.3636,  0.3067, -1.0327,  1.3824]])

In [ ]:
d.shape

torch.Size([4, 5])

In [ ]:
torch.argmin(d, dim=1)

tensor([1, 4, 2, 1])

In [ ]:
torch.argmax(d, dim=1)

tensor([2, 0, 0, 0])

If it is either a row or column, it is a single dimension and is called a 1D tensor. If the input is a matrix, in which rows and columns are present, it is called a 2D tensor. If it is more than two-dimensional, it is called a multidimensional tensor.

## torch.cat

Now, let’s create a sample 2D tensor and perform indexing and concatenation by using the concat operation on the tensors.

In [ ]:
x = torch.rand(4,5)
x

tensor([[0.3532, 0.9624, 0.5881, 0.5701, 0.5513],
        [0.5326, 0.5210, 0.0655, 0.9826, 0.9773],
        [0.1558, 0.6236, 0.9133, 0.5968, 0.7151],
        [0.8724, 0.7122, 0.4096, 0.0844, 0.2642]])

In [ ]:
# concatenate two tensors

torch.cat((x,x))

tensor([[0.3532, 0.9624, 0.5881, 0.5701, 0.5513],
        [0.5326, 0.5210, 0.0655, 0.9826, 0.9773],
        [0.1558, 0.6236, 0.9133, 0.5968, 0.7151],
        [0.8724, 0.7122, 0.4096, 0.0844, 0.2642],
        [0.3532, 0.9624, 0.5881, 0.5701, 0.5513],
        [0.5326, 0.5210, 0.0655, 0.9826, 0.9773],
        [0.1558, 0.6236, 0.9133, 0.5968, 0.7151],
        [0.8724, 0.7122, 0.4096, 0.0844, 0.2642]])

The sample x tensor can be used in 3D as well. Again, there are two different options to create three-dimensional tensors; the third dimension can be extended over rows or columns.

In [ ]:
# concatenate n times based on array size, over column

torch.cat((x,x,x),1)

tensor([[0.3532, 0.9624, 0.5881, 0.5701, 0.5513, 0.3532, 0.9624, 0.5881, 0.5701,
         0.5513, 0.3532, 0.9624, 0.5881, 0.5701, 0.5513],
        [0.5326, 0.5210, 0.0655, 0.9826, 0.9773, 0.5326, 0.5210, 0.0655, 0.9826,
         0.9773, 0.5326, 0.5210, 0.0655, 0.9826, 0.9773],
        [0.1558, 0.6236, 0.9133, 0.5968, 0.7151, 0.1558, 0.6236, 0.9133, 0.5968,
         0.7151, 0.1558, 0.6236, 0.9133, 0.5968, 0.7151],
        [0.8724, 0.7122, 0.4096, 0.0844, 0.2642, 0.8724, 0.7122, 0.4096, 0.0844,
         0.2642, 0.8724, 0.7122, 0.4096, 0.0844, 0.2642]])

In [ ]:
# concatenate n times based on array size, over rows

torch.cat((x,x,x),0)

tensor([[0.3532, 0.9624, 0.5881, 0.5701, 0.5513],
        [0.5326, 0.5210, 0.0655, 0.9826, 0.9773],
        [0.1558, 0.6236, 0.9133, 0.5968, 0.7151],
        [0.8724, 0.7122, 0.4096, 0.0844, 0.2642],
        [0.3532, 0.9624, 0.5881, 0.5701, 0.5513],
        [0.5326, 0.5210, 0.0655, 0.9826, 0.9773],
        [0.1558, 0.6236, 0.9133, 0.5968, 0.7151],
        [0.8724, 0.7122, 0.4096, 0.0844, 0.2642],
        [0.3532, 0.9624, 0.5881, 0.5701, 0.5513],
        [0.5326, 0.5210, 0.0655, 0.9826, 0.9773],
        [0.1558, 0.6236, 0.9133, 0.5968, 0.7151],
        [0.8724, 0.7122, 0.4096, 0.0844, 0.2642]])

## torch.chunk

A tensor can be split between multiple chunks. Those small chunks can be created along dim rows and dim columns. The following example shows a sample tensor of size (4,4). The chunk is created using the third argument in the function, as 0 or 1.

In [ ]:
a = torch.rand(4,4)
print(a)

tensor([[0.2023, 0.5101, 0.1460, 0.8175],
        [0.5985, 0.2834, 0.2103, 0.6638],
        [0.3803, 0.5955, 0.5470, 0.5622],
        [0.4308, 0.4020, 0.3828, 0.6928]])


In [ ]:
torch.chunk(a,2)

(tensor([[0.2023, 0.5101, 0.1460, 0.8175],
         [0.5985, 0.2834, 0.2103, 0.6638]]),
 tensor([[0.3803, 0.5955, 0.5470, 0.5622],
         [0.4308, 0.4020, 0.3828, 0.6928]]))

In [ ]:
torch.chunk(a,2,0)

(tensor([[0.2023, 0.5101, 0.1460, 0.8175],
         [0.5985, 0.2834, 0.2103, 0.6638]]),
 tensor([[0.3803, 0.5955, 0.5470, 0.5622],
         [0.4308, 0.4020, 0.3828, 0.6928]]))

In [ ]:
torch.chunk(a,2,1)

(tensor([[0.2023, 0.5101],
         [0.5985, 0.2834],
         [0.3803, 0.5955],
         [0.4308, 0.4020]]),
 tensor([[0.1460, 0.8175],
         [0.2103, 0.6638],
         [0.5470, 0.5622],
         [0.3828, 0.6928]]))

## torch.gather

The gather function collects elements from a tensor and places it in another tensor using an index argument. The index position is determined by the LongTensor function in PyTorch.

In [ ]:
torch.Tensor([[11,12],[23,24]])

tensor([[11., 12.],
        [23., 24.]])

In [ ]:
torch.gather(torch.Tensor([[11,12],[23,24]]), 1,
             torch.LongTensor([[0,0],[1,0]]))

tensor([[11., 11.],
        [24., 23.]])

In [ ]:
torch.gather(torch.Tensor([[11,12],[23,24]]), 0,
             torch.LongTensor([[0,0],[1,0]]))

tensor([[11., 12.],
        [23., 12.]])

In [ ]:
# the 1D tensor containing the indices to index
torch.LongTensor([[0,0],[1,0]])

tensor([[0, 0],
        [1, 0]])

## torch.index_select

The LongTensor function or the index select function can be used to fetch relevant values from a tensor. The following sample code shows two options: selection along rows and selection along columns. If the second argument is 0, it is for rows. If it is 1, then it is along the columns.

In [ ]:
a = torch.randn(4,4)
a

tensor([[ 0.6241,  0.9364,  0.7707, -0.1255],
        [-0.0446, -0.2705,  1.1501,  1.4566],
        [-0.0417,  0.7463,  0.3322, -0.1859],
        [-1.4301, -1.4317,  2.1155, -1.1853]])

In [ ]:
indices = torch.LongTensor([0,2])

In [ ]:
torch.index_select(a, 0, indices)

tensor([[ 0.6241,  0.9364,  0.7707, -0.1255],
        [-0.0417,  0.7463,  0.3322, -0.1859]])

In [ ]:
torch.index_select(a, 1, indices)

tensor([[ 0.6241,  0.7707],
        [-0.0446,  1.1501],
        [-0.0417,  0.3322],
        [-1.4301,  2.1155]])

## torch.nonzero

It is a common practice to check non-missing values in a tensor, the objective is to identify non-zero elements in a large tensor.

In [ ]:
# identify null input tensors using nonzero function
torch.nonzero(torch.tensor([10,00,23,0,0.0]))

tensor([[0],
        [2]])

In [ ]:
# identify null input tensors using nonzero function
torch.nonzero(torch.Tensor([10,00,23,0,0.0]))

tensor([[0],
        [2]])

## torch.split

Restructuring the input tensors into smaller tensors not only fastens the calculation process, but also helps in distributed computing. The split function splits a long tensor into smaller tensors.

In [ ]:
# splitting the tensor into small chunks
torch.split(torch.tensor([12,21,32,43,54,56,65,76]), 2)

(tensor([12, 21]), tensor([32, 43]), tensor([54, 56]), tensor([65, 76]))

In [ ]:
# splitting the tensor into small chunks
torch.split(torch.tensor([12,21,32,43,54,56,65,76]), 3)

(tensor([12, 21, 32]), tensor([43, 54, 56]), tensor([65, 76]))

## torch.transpose

Now, let’s have a look at examples of how the input tensor can be resized given the computational difficulty. The transpose function is primarily used to reshape tensors. There are two ways of writing the transpose function: .t and .transpose.

In [ ]:
# how to reshape the tensors along a new dimension

In [ ]:
x

tensor([[0.3532, 0.9624, 0.5881, 0.5701, 0.5513],
        [0.5326, 0.5210, 0.0655, 0.9826, 0.9773],
        [0.1558, 0.6236, 0.9133, 0.5968, 0.7151],
        [0.8724, 0.7122, 0.4096, 0.0844, 0.2642]])

In [ ]:
x.t() # transpose is one option to change the shape of the tensor

tensor([[0.3532, 0.5326, 0.1558, 0.8724],
        [0.9624, 0.5210, 0.6236, 0.7122],
        [0.5881, 0.0655, 0.9133, 0.4096],
        [0.5701, 0.9826, 0.5968, 0.0844],
        [0.5513, 0.9773, 0.7151, 0.2642]])

In [ ]:
x.transpose(1,0)

tensor([[0.3532, 0.5326, 0.1558, 0.8724],
        [0.9624, 0.5210, 0.6236, 0.7122],
        [0.5881, 0.0655, 0.9133, 0.4096],
        [0.5701, 0.9826, 0.5968, 0.0844],
        [0.5513, 0.9773, 0.7151, 0.2642]])

## torch.unbind

The unbind function removes a dimension from a tensor. To remove the dimension row, the 0 value needs to be passed. To remove a column, the 1 value needs to be passed.

In [ ]:
x

tensor([[0.3532, 0.9624, 0.5881, 0.5701, 0.5513],
        [0.5326, 0.5210, 0.0655, 0.9826, 0.9773],
        [0.1558, 0.6236, 0.9133, 0.5968, 0.7151],
        [0.8724, 0.7122, 0.4096, 0.0844, 0.2642]])

In [ ]:
torch.unbind(x, 1) # dim=1, removing a column

(tensor([0.3532, 0.5326, 0.1558, 0.8724]),
 tensor([0.9624, 0.5210, 0.6236, 0.7122]),
 tensor([0.5881, 0.0655, 0.9133, 0.4096]),
 tensor([0.5701, 0.9826, 0.5968, 0.0844]),
 tensor([0.5513, 0.9773, 0.7151, 0.2642]))

In [ ]:
torch.unbind(x) # dim=0, removing a row

(tensor([0.3532, 0.9624, 0.5881, 0.5701, 0.5513]),
 tensor([0.5326, 0.5210, 0.0655, 0.9826, 0.9773]),
 tensor([0.1558, 0.6236, 0.9133, 0.5968, 0.7151]),
 tensor([0.8724, 0.7122, 0.4096, 0.0844, 0.2642]))

## torch.add, torch.mul

Mathematical functions are the backbone of implementing any algorithm in PyTorch; therefore, it is needed to go through functions that help perform arithmetic-based operations. A scalar is a single value, and a tensor 1D is a row, like NumPy. The scalar multiplication and addition with a 1D tensor are done using the add and mul functions.

In [ ]:
x

tensor([[0.3532, 0.9624, 0.5881, 0.5701, 0.5513],
        [0.5326, 0.5210, 0.0655, 0.9826, 0.9773],
        [0.1558, 0.6236, 0.9133, 0.5968, 0.7151],
        [0.8724, 0.7122, 0.4096, 0.0844, 0.2642]])

In [ ]:
torch.add(x,20)

tensor([[20.3532, 20.9624, 20.5881, 20.5701, 20.5513],
        [20.5326, 20.5210, 20.0655, 20.9826, 20.9773],
        [20.1558, 20.6236, 20.9133, 20.5968, 20.7151],
        [20.8724, 20.7122, 20.4096, 20.0844, 20.2642]])

In [ ]:
x

tensor([[0.3532, 0.9624, 0.5881, 0.5701, 0.5513],
        [0.5326, 0.5210, 0.0655, 0.9826, 0.9773],
        [0.1558, 0.6236, 0.9133, 0.5968, 0.7151],
        [0.8724, 0.7122, 0.4096, 0.0844, 0.2642]])

In [ ]:
torch.mul(x,2)

tensor([[0.7065, 1.9247, 1.1762, 1.1402, 1.1025],
        [1.0652, 1.0421, 0.1310, 1.9653, 1.9547],
        [0.3116, 1.2473, 1.8266, 1.1936, 1.4301],
        [1.7448, 1.4245, 0.8192, 0.1687, 0.5284]])

Combined mathematical operations, such as expressing linear equations as tensor operations can be done using the following sample script. Here we express the outcome y object as a linear combination of beta values times the independent x object, plus the constant term.

In [ ]:
intercept = torch.randn(1)
intercept

tensor([-0.3002])

In [ ]:
x = torch.randn(2,2)
x

tensor([[-1.1125, -0.1628],
        [ 0.6744,  1.0753]])

In [ ]:
beta = 0.7456
beta

0.7456

Output = Constant + (beta * Independent)


In [ ]:
torch.mul(intercept, x)

tensor([[ 0.3340,  0.0489],
        [-0.2025, -0.3228]])

In [ ]:
torch.mul(x, beta)

tensor([[-0.8295, -0.1214],
        [ 0.5028,  0.8017]])

In [ ]:
## y = intercept + (beta * x)
torch.add(torch.mul(intercept,x), torch.mul(x,beta)) # tensor y

tensor([[-0.4955, -0.0725],
        [ 0.3004,  0.4789]])

## torch.ceil, torch.floor

Like NumPy operations, the tensor values must be rounded up by using either the ceiling or the flooring function, which is done using the following syntax.

In [ ]:
# how to round up tensor values
torch.manual_seed(1234)
torch.randn(5,5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [ ]:
torch.manual_seed(1234)
torch.ceil(torch.randn(5,5))

tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])

In [ ]:
torch.manual_seed(1234)
torch.floor(torch.randn(5,5))

tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])

## torch.clamp

Limiting the values of any tensor within a certain range can be done using the minimum and maximum argument and using the clamp function. The same function can apply minimum and maximum in parallel or any one of them to any tensor, be it 1D or 2D; 1D is the far simpler version. The following example shows the implementation in  a 2D scenario.

In [ ]:
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3, max=0.4)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  0.4000],
        [ 0.0000, -0.3000,  0.4000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [ ]:
# truncate with only lower limit
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  1.0000],
        [ 0.0000, -0.3000,  1.0000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [ ]:
# truncate with only upper limit
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), max=0.3)

tensor([[-1.0000, -1.0000,  0.0000, -1.0000,  0.0000],
        [ 0.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-2.0000, -1.0000,  0.0000, -1.0000,  0.3000],
        [ 0.0000, -2.0000,  0.3000, -1.0000, -1.0000],
        [-2.0000,  0.0000, -1.0000,  0.0000,  0.0000]])

## torch.exp

In [ ]:
# compute the exponential of a tensor
torch.exp(x)

tensor([[0.3287, 0.8497],
        [1.9629, 2.9308]])

In [ ]:
np.exp(x)

tensor([[0.3287, 0.8497],
        [1.9629, 2.9308]])

In [ ]:
# how to get the fractional portion of each tensor
torch.add(x,10)

tensor([[ 8.8875,  9.8372],
        [10.6744, 11.0753]])

In [ ]:
torch.frac(torch.add(x,10))

tensor([[0.8875, 0.8372],
        [0.6744, 0.0753]])

## torch.log, torch.pow

The following syntax explains the logarithmic values in a tensor. The values with a negative sign are converted to nan. The power function computes the exponential of any value in a tensor.

In [ ]:
# compute the log of the values in a tensor

In [ ]:
x

tensor([[-1.1125, -0.1628],
        [ 0.6744,  1.0753]])

In [ ]:
torch.log(x) # log of negatives are nan

tensor([[    nan,     nan],
        [-0.3939,  0.0726]])

In [ ]:
# to rectify the negative values do a power transformation
torch.pow(x,2)

tensor([[1.2376, 0.0265],
        [0.4548, 1.1562]])

## torch.sigmoid, torch.sqrt

To compute the transformation functions (i.e., sigmoid, hyperbolic tangent, radial basis function, and so forth, which are the most commonly used transfer functions in deep learning), you must construct the tensors. The following sample script shows how to create a sigmoid function and apply it on a tensor.

In [ ]:
x

tensor([[-1.1125, -0.1628],
        [ 0.6744,  1.0753]])

In [ ]:
# how to compute the sigmoid of the input tensor

torch.sigmoid(x)

tensor([[0.2474, 0.4594],
        [0.6625, 0.7456]])

In [ ]:
# finding the square root of the values

torch.sqrt(x)

tensor([[   nan,    nan],
        [0.8212, 1.0370]])

# Conclusion

This chapter is a refresher for people who have prior experience in PyTorch and Python. It is a basic building block for people who are new to the PyTorch framework. Before starting the advanced topics, it is important to become familiar with the terminology and basic syntaxes. The next chapter is on using PyTorch to implement probabilistic models, which includes the creation of random variables, the application of statistical distributions, and making statistical inferences.